// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzZADThiLBkr7vCKQbiH71QjNsGtMKrQ0',
    appId: '1:786686607287:web:049ab9fe6ad7187cf6b232',
    messagingSenderId: '786686607287',
    projectId: 'unn-ucs',
    authDomain: 'unn-ucs.firebaseapp.com',
    storageBucket: 'unn-ucs.firebasestorage.app',
    measurementId: 'G-HV0C1LYW19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSMd8T-q0-DXKuqTCc7pUEViGy5z9uclc',
    appId: '1:786686607287:android:44b6426b0d98b83ef6b232',
    messagingSenderId: '786686607287',
    projectId: 'unn-ucs',
    storageBucket: 'unn-ucs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYP2y6dbifnQgFWe4xY8mlcNlGRS6o5v8',
    appId: '1:786686607287:ios:b3ce552a22c58b5ef6b232',
    messagingSenderId: '786686607287',
    projectId: 'unn-ucs',
    storageBucket: 'unn-ucs.firebasestorage.app',
    iosBundleId: 'com.example.ucs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYP2y6dbifnQgFWe4xY8mlcNlGRS6o5v8',
    appId: '1:786686607287:ios:b3ce552a22c58b5ef6b232',
    messagingSenderId: '786686607287',
    projectId: 'unn-ucs',
    storageBucket: 'unn-ucs.firebasestorage.app',
    iosBundleId: 'com.example.ucs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzZADThiLBkr7vCKQbiH71QjNsGtMKrQ0',
    appId: '1:786686607287:web:7c145eccbc030fbef6b232',
    messagingSenderId: '786686607287',
    projectId: 'unn-ucs',
    authDomain: 'unn-ucs.firebaseapp.com',
    storageBucket: 'unn-ucs.firebasestorage.app',
    measurementId: 'G-26X4TGQKY4',
  );
}
